version: '3.8'

services:

# Node js services
  nodejs-app:
         build: .
         ports:
            - 5000:5000
         environment:
            SERVER_PORT: 5000
            DATABASE_URL: "mongodb://mongodb_auth:27017/CleanArchitecture"
         depends_on: 
            - mongodb_auth
            - rabbitmq

# mongodb_auth Services

  mongodb_auth:
    image: mongo:latest
    container_name: mongodb_auth-container
    restart: always
    volumes:
      - mongodb_auth:/data/db
    

# Rabbitmq services

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_auth-container
    restart: always
    ports:
      - "15672:15672"
    networks:
          - rabbitmq-network

volumes: 
  mongodb_auth: {}

networks:
  rabbitmq-network:
    external: true
   











